Various updates to remote-config
ddev/remote-config pull request #31
Opened 2024-12-03 22:11 UTC by rfay

## The Issue

Catch up on remote-config

2024-12-03 22:44 UTC, rfay commented
Any suggestions on content changes or additional items are welcome, thanks!

2024-12-04 01:06 UTC, tyler36 requested changes

2024-12-04 01:06 UTC, tyler36 commented on remote-config.jsonc
> +          "message": "You're invited to the DDEV Advisory Group, bimonthly on first Wednesday, see the schedule and sign up at https://www.meetup.com/ddev-events/"
```suggestion
          "message": "You're invited to the DDEV Advisory Group, first Wednesday every two months, see the schedule and sign up at https://www.meetup.com/ddev-events/"
```

I always get confused with "bimonthly". Happy to go with "every odd-numbered month", "every other month".

2024-12-04 01:06 UTC, tyler36 commented on remote-config.jsonc
>          },
```suggestion
        {
          "message": "A key goal for DDEV in 2025 is to make it possible for maintainer Stas Zhuk to work full-time on DDEV, see https://ddev.com/blog/lets-fund-stas-maintainer/"
        },
```

Bump year to 2025, assuming this is still a goal.

2024-12-04 09:46 UTC, stasadev requested changes
I noticed old Discord link, and old mailpit link:

```diff
-https://discord.gg/hCZFfAMc5k
+https://discord.gg/5wjP76mBJD
```

```diff
-ddev launch -m
+ddev mailpit
```

2024-12-04 09:46 UTC, stasadev commented on remote-config.jsonc
> +          "message": "DDEV allows you to rapidly profile the performance of your PHP code using XHProf with `ddev xhprof on`. Try out https://github.com/ddev/ddev-xhgui !"
We have a similar entry, please remove one of them:

```
"Want to profile your code in an improved more beautiful manner with Xhprof? Try out @tyler36's https://github.com/ddev/ddev-xhgui"
```

2024-12-04 09:46 UTC, stasadev commented on remote-config.jsonc
> +          "message": "Want to know more about using vite with DDEV? The Vite blog is superbly maintained by Matthias Andrasch with the latest information: https://ddev.com/blog/working-with-vite-in-d
We have a similar entry, please remove one of them:

```
"Read about Vite in DDEV, thanks to Matthias Andrasch: https://ddev.com/blog/working-with-vite-in-ddev/"
```

2024-12-04 09:46 UTC, stasadev commented on remote-config.jsonc
> +
```suggestion
```

2024-12-04 18:24 UTC, stasadev approved these changes

2024-12-04 18:28 UTC, merged